### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 3086 ?

### ISSUE THREAD

**Issue by mathieu-lemire** [XiaoleiLiuBio/G2P#2]
Are you supporting your software, I see an open issue with no follow up since November.  I want to know if I need to switch to something else. I also have the following issue. 

Trying to simulate larger sample size by following your examples and dataset, I get the following:

java -jar kG2P.jar --ped AG.ped --map AG.map  --outgen output  --rn 5000 --block 4
Simulation .ped without .pop
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3086
        at cn.ykp.core.CoreHandler.handlerHasBlock(CoreHandler.java:147)
        at cn.ykp.app.APP.<init>(APP.java:247)
        at cn.ykp.app.APP.main(APP.java:594)

Using --rn 3086 is fine, using --rn 3087 it fails.

Using my own dataset, I get this error at a lower sample size (--rn 1001) 

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by XiaoleiLiuBio** [comment]
Thank you for using G2P. We will check your issue and update the tool soon. BTW, as shown in G2P GitHub website, more abundant simulation functions could be referred to our newly developed package SIMER (https://github.com/xiaolei-lab/SIMER) for simulation of life science and breeding.

**Comment by XiaoleiLiuBio** [comment]
The ‘rn’ should be set to a number less than the marker size in AG.ped file. It seems that you are using the demo data and it has only 3086 markers.
